### ISSUE TITLE
Milmon Home

### ISSUE THREAD

**Issue by Molmin** [Molmin/molmin.github.io#1]

**Comment by wxuyuan** [comment]
居然改排版了

**Comment by Molmin** [comment]
> @wxuyuan
> 居然改排版了

明明还改了加密函数

**Comment by wxuyuan** [comment]
强！

**Comment by Molmin** [comment]
> @wxuyuan
> 强！

严禁考试划水

**Comment by wxuyuan** [comment]
> > @wxuyuan
> > 强！
> 
> 严禁考试划水

那我是如何被发现的（

**Comment by Molmin** [comment]
> @wxuyuan
> > > @wxuyuan
> > > 强！
> > 
> > 严禁考试划水
> 
> 那我是如何被发现的（

GitHub 的提示邮件打扰我写题（

**Comment by Molmin** [comment]
草写完139行代码才发现算法假了呜呜呜

**Comment by yyf525** [comment]
原来在这里发。。。

**Comment by Molmin** [comment]
> @yyf525
> 原来在这里发。。。

好像只要登录要挂vpn，登一次之后vpn撤掉导出缓存也可以正常评论
当然也可以在issues里评论

**Comment by wxuyuan** [comment]
[林子洋的简历](http://linziyang.github.io/%E7%AE%80%E5%8E%86) %%%

**Comment by hexuben** [comment]
lzy在我前面搜gitalk怎么评论。。

**Comment by linziyang2** [comment]
我，没有数学思维，没有擦亮思想，我很平庸。 --宣誓人，Milmon。

**Comment by linziyang2** [comment]
hexuben!!!

**Comment by linziyang2** [comment]
@wxuyuan 既然你觉得linziyang是我的号，
# $$\color{red}{那就拉黑他吧！！！}$$

**Comment by Molmin** [comment]
> @linziyang2
> 我，没有数学思维，没有擦亮思想，我很平庸。 --宣誓人，林子洋。

稍微有点颜色给你就灿烂了啊，别骄傲，嘘嘘还在我手里呢

**Comment by linziyang2** [comment]
> @wxuyuan 既然你觉得linziyang是我的号，
> # milmon别乱改！！！

**Comment by Molmin** [comment]
123
